site_name: 云原生生态圈
nav:
  - 主页: "index.md"
  - 关于: "about.md"
  - 自动化: "devops.md"
theme: material
repo_url: https://github.com/linuxermaster/cloudnativecosystem_mkdocs.git
repo_name: "Opening on Github"
site_description: "这是一个mkdocs的demo测试知识库网站"
site_author: "Marionxue"
copyright: "1994 - 2020"
